template: rolling_aggregation_template
template_fields:
  partition_field: day
  window_lengths: [7,60]
  aggregations: [cumulative_sum]
  window_type: day
  join_key: tracking_id
  features:
    - duration_partial_series_obs_period
    - count_search_used_obs_period
    - count_empty_search_obs_period
    - count_pdp_page_obs_period
    - count_get_premium_click
    - count_sessions_obs_period
    - count_empty_sessions_obs_period_qualified
    - usage_hrs_obs_period
    - ad_duration_obs_period
    - session_duration_mins_obs_period
    - device_duration_Amazon_Fire_TV
    - device_duration_Android_Mobile
    - device_duration_Android_TV
    - device_duration_Apple_TV
    - device_duration_Cox
    - device_duration_Ios_Mobile
    - device_duration_LG_Smart_TV
    - device_duration_PS4
    - device_duration_Roku
    - device_duration_Vizio
    - device_duration_Www
    - device_duration_Xbox_One
    - device_duration_Xfinity
    - daypart_duration_MORNING
    - daypart_duration_DAYTIME
    - daypart_duration_EVENING
    - daypart_duration_LATE_NIGHT
    - daypart_duration_OVERNIGHT
    - daypart_duration_PRIMETIME
    - daypart_duration_WEEKEND
    - genre_duration_action_obs_period
    - genre_duration_comedy_obs_period
    - genre_duration_crime_obs_period
    - genre_duration_documentary_obs_period
    - genre_duration_drama_obs_period
    - genre_duration_entertainment_obs_period
    - genre_duration_gameshow_obs_period
    - genre_duration_horror_obs_period
    - genre_duration_kids_obs_period
    - genre_duration_lifestyle_obs_period
    - genre_duration_music_obs_period
    - genre_duration_news_obs_period
    - genre_duration_reality_obs_period
    - genre_duration_scifi_obs_period
    - genre_duration_sports_obs_period
    - genre_duration_talk_obs_period
    - genre_duration_thriller_obs_period
    - genre_duration_western_obs_period
    - duration_platform_TV_VOD_obs_period
    - duration_platform_Shortform_obs_period
    - duration_platform_Movie_obs_period
    - duration_popular_SH_titles_obs_period
    - duration_popular_H_titles_obs_period
    - duration_popular_M_titles_obs_period
    - duration_popular_L_titles_obs_period
    - count_cancel_help_visit_obs_period
    - count_cancel_page_visit_obs_period
    - total_time_to_content
    - total_session_duration_mins_obs_period
    - cnt_for_avg_session_duration_obs_period
    - count_active_days_obs_period
    - count_active_days_obs_period_qualified
  upstream_table: user_visit_features_rollup
